name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a CI/CD test script
        run: echo 'I hopethis makes the CI/CD Workflow Running Successfully!'
